### ISSUE TITLE
URL's are changed.

### ISSUE THREAD

**Issue by sanjaypradeep** [shubhamc183/way2sms#2]
Hi Shubhamc, 

Recently the URL's of way2sms.com has been changed. 

```
self.msg_url='http://site24.way2sms.com/smstoss.action'
self.msg_url='http://site24.way2sms.com/schedulesms.action'
self.msg_left_url='http://site24.way2sms.com/sentSMS?Token='+self.jsid
```
If someone creates a object and do object.send(number, message). It will return a 200 response, but originally the SMS are not sent. 

Here is the current URL structure followed in recently in the site.

`http://site21.way2sms.com/main.action?Token=F161C7798A67FBDC9E3873774357290E.w804&section=s`

then changes would like this, 

`self.msg_left_url ='http://site21.way2sms.com/main.action?Token='+self.jsid+'&section='+self.s`

Here I'm appending **&section= self.s**

`self.s` is a sessionObject, we can't concatenate session object with a str. If this is corrected, then sms can be sent, number of sms sent can also be viewed..

Let's get in touch to discuss more if you wish. 

Thanks,
Sanjay

**Comment by shubhamc183** [comment]
The messages are still being sent, http://site24.way2sms.com/Login1.action is the post login URL.
Maybe there is a confusion between site24 and site21.

**Comment by ayushad** [comment]
Traceback (most recent call last):
  File "F:/xampp/cgi-bin/project/smstry.py", line 4, in <module>
    q.msgSentToday()
  File "F:/xampp/cgi-bin/project\way2sms.py", line 51, in msgSentToday
    self.t=self.soup.find("div",{"class":"hed"}).h2.text		# div element with class "hed" -> h2
AttributeError: 'NoneType' object has no attribute 'h2'





getting this error while running program

**Comment by shubhamc183** [comment]
You are getting this error because you didn't get logged in.
self.soup.find("div",{"class":"hed"}) returns None.
[see](https://github.com/shubhamc183/way2sms/commit/047812269d36a541a3b1ee8367c27260d3b4095f) this

**Comment by shubhamc183** [comment]
[](url)

**Comment by shubhamc183** [comment]
[](url)

**Comment by SurenderHarsha** [comment]
Why would you reopen this.?

**Comment by shubhamc183** [comment]
By mistake, thanks for notifying [harsha](https://github.com/SurenderHarsha)..!
