### ISSUE TITLE
Can't login, once check credential..! please guide me.credentials are correct.

### ISSUE THREAD

**Issue by LinaD** [shubhamc183/way2sms#5]
import requests
from bs4 import BeautifulSoup

#".*//"
class sms:
	def __init__(self,username,password):

		'''
		Takes username and password as parameters for constructors
		and try to log in
		'''

		self.url='http://www.way2sms.com/Login1.action?'

		self.cred={'username': username, 'password': password}

		self.s=requests.Session()			# Session because we want to maintain the cookies

		'''
		changing s.headers['User-Agent'] to spoof that python is requesting
		'''
		print("username"+username)

		self.s.headers['User-Agent'] = "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
		self.s.headers['Referer'] = "http://www.way2sms.com/content/index.html"    #http://www.way2sms.com/content/index.html
		self.s.headers['Host'] = "www.way2sms.com"
		print("host")
		print(self.url)

		self.q=self.s.post(self.url,data=self.cred)
		print("details")

		self.loggedIn=False				# a variable of knowing whether logged in or not
		print("self.loggedIn"+self.loggedIn)

		if "http://www.way2sms.com/main.action" in self.q.url:			# http status 200 == OKhttp://www.way2sms.com/main.action;jsessionid=8AC39E41522005C2882BFA783D5B3389.w803?Token=8AC39E41522005C2882BFA783D5B3389.w803&section=s

			print("Successfully logged in..!")

			self.loggedIn=True

		else:

			print("Can't login, once check credential..!")

			self.loggedIn=False

		self.jsid=self.s.cookies.get_dict()['JSESSIONID'][4:]	    # JSID is the main KEY as JSID are produced every time a session satrts

	def msgSentToday(self):

		'''
		Returns number of SMS sent today as there is a limit of 100 messages everyday..!
		'''

		if self.loggedIn == False:
			print("Can't perform since NOT logged in..!")
			return -1

		self.msg_left_url='http://www.way2sms.com/sentSMS?Token='+self.jsid

		self.q=self.s.get(self.msg_left_url)

		self.soup=BeautifulSoup(self.q.text,'html.parser')		#we want the number of messages sent which is present in the

		self.t=self.soup.find("div",{"class":"hed"}).h2.text		# div element with class "hed" -> h2

		self.sent=0

		for self.i in self.t:

			if self.i.isdecimal():

				self.sent=10*self.sent+int(self.i)

		return self.sent

	def send(self,mobile_no,msg):

		'''
		Sends the message to the given mobile number
		'''

		if self.loggedIn == False:
			print("Can't perform since NOT logged in..!")
			return False

		if len(msg)>139 or len(mobile_no)!=10 or not mobile_no.isdecimal():	#checks whether the given message is of length more than 139

			return False							#or the mobile_no is valid

		self.payload={'ssaction':'ss',
				'Token':self.jsid,					#inorder to visualize how I came to these payload,
			        'mobile':mobile_no,					#must see the NETWORK section in Inspect Element
       				 'message':msg,						#while messagin someone from your browser
			        'msgLen':'129'
       			     }

		self.msg_url='http://www.way2sms.com/smstoss.action'

		self.q=self.s.post(self.msg_url,data=self.payload)

		if self.q.status_code==200:

			return True

		else:
			return False

	def sendLater(self, mobile_no, msg, date, time):				#Function for future SMS feature.
											#date must be in dd/mm/yyyy format
											#time must be in 24hr format. For ex: 18:05

		if self.loggedIn == False:
			print("Can't perform since NOT logged in..!")
			return False
		
		if len(msg)>139 or len(mobile_no)!=10 or not mobile_no.isdecimal():
			return False

		dateparts = date.split('/')			#These steps to check for valid date and time and formatting
		timeparts = time.split(':')
		if int(dateparts[0])<1 or int(dateparts[0])>32 or int(dateparts[1])>12 or int(dateparts[1])<1 or int(dateparts[2])<2017 or int(timeparts[0])<0 or int(timeparts[0])>23 or int(timeparts[1])>59 or int(timeparts[1])<0:
			return False
		date = dateparts[0].zfill(2) + "/" + dateparts[1].zfill(2) + "/" + dateparts[2]
		time = timeparts[0].zfill(2) + ":" + timeparts[1].zfill(2)

		self.payload={'Token':self.jsid,
				'mobile':mobile_no,
				'sdate':date,
				'stime':time,
				'message':msg,
				'msgLen':'129'
				}

		self.msg_url='http://www.way2sms.com/schedulesms.action'
		self.q=self.s.post(self.msg_url, data=self.payload)

		if self.q.status_code==200:
			return True
		else:
			return False

	def logout(self):

		self.s.get('http://www.way2sms.com/entry?ec=0080&id=dwks')

		self.s.close()								# close the Session

		self.loggedIn=False
		
***************Error********************************

>>>import way2sms.py
>>>q=way2sms.sms('9458545666','KSD8')
Can't login, once check credential..!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\Python\Python36\way2sms.py", line 45, in __init__
    self.jsid=self.s.cookies.get_dict()['JSESSIONID'][4:]           # JSID is th
e main KEY as JSID are produced every time a session satrts
KeyError: 'JSESSIONID'
>>>

**Comment by shubhamc183** [comment]
Have you registered your account with the above mobile number?

**NEVER POST YOUR PASSWORDS LIKE THIS ANYWHERE**

**Comment by LinaD** [comment]
yes..and password and mobile numbers shown here are dummy.just for better understanding...

**Comment by imnotkk** [comment]
Any leads?

**Comment by muthukumarece5** [comment]
yes me too observed login error!. I think they are changed way2sms API.
self.url='http://www.way2sms.com/Login1.action?' It is a invalid link!.

Error:
print("DEBUG:",self.q.url)
DEBUG: http://www.way2sms.com/Logout

Developer:
Could you please let us know how we can find out which API is working now.

Thanks,
Muthu

**Comment by shubhamc183** [comment]
First of all thanks for using this repo.
@LinaD @imnotkk @muthukumarece5 I would like to apologize for not giving time to update this repo.

Way2sms changed their website a lot this time, so changed some url.

Future Sms has this time limitation from their end because of DND.

Number of Sms sent I have not figured out how to code.

Pull request are welcome..!

**Comment by muthukumarece5** [comment]
Thanks you so much for valuable fix.

Thanks,
Muthu

**Comment by LinaD** [comment]
Thank you.. shubhamc183.. happy with your response. But still on my server it is not working,, may be because of  I m working on jump server.. Could you please help me in how to set proxy in this.. or any other solution you have?

**Comment by shubhamc183** [comment]
Are you behind some Proxy?

Windows/ Linux?

**Comment by LinaD** [comment]
yes. Windows proxy. Trying on jump server.

**Comment by shubhamc183** [comment]
```
import requests

proxies = {
    'http': 'http://user:pass@10.10.1.0:3128',
    'https': 'http://user:pass@10.10.1.0:3128',
}

# Create the session and set the proxies.
s = requests.Session()
s.proxies = proxies

# Make the HTTP request through the session.
r = s.get('http://www.showmemyip.com/')

# Check if the proxy was indeed used (the text should contain the proxy IP).
print(r.text)
```
