### ISSUE TITLE
Is it a valid link? They were changed API.

### ISSUE THREAD

**Issue by muthukumarece5** [shubhamc183/way2sms#6]
https://github.com/shubhamc183/way2sms/blob/7a7cae4759249ff1125f565b8595f7fa5d187bc1/way2sms.py#L15

**Comment by muthukumarece5** [comment]
@shubhamc183

**Comment by shubhamc183** [comment]
Yes, they update their website a lot this time.

Number of sms sent not figured out yet how to code.

Thanks for using.
