### ISSUE TITLE
Getting error way2sms has no sms attribute.


### ISSUE THREAD

**Issue by ameybh** [shubhamc183/way2sms#9]
Created a driver code file with all the code to run and send a test message :
way2sms.driver.py
```
import way2sms

q=way2sms.sms(number,password)

q.send( '9*******', 'test message' )
q.logout();
```

Then, ran the following command:

```
$ python3 way2sms.driver.py
Traceback (most recent call last):
  File "way2sms.driver.py", line 3, in <module>
    q=way2sms.sms(7678058981,A7292T)
AttributeError: module 'way2sms' has no attribute 'sms'

```
Please resolve. 
Another query, is the username as same as my phone number; and, do I need to prefix the number with +91 for India's country code?

**Comment by shubhamc183** [comment]
download the code, add in your PYTHONPATH, or simply run the code at same repository level where you place the file.

**Comment by amrs-tech** [comment]
use way2sms.Sms(....)
